server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.190:3306/sparrow-activiti7?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&nullCatalogMeansCurrent=true
    username: root
    password: 123456
  activiti:
    database-schema-update: true #启动时检查数据库，不存在则创建
    history-level: full #表示哪种情况下使用历史表，这里配置full表示全部记录历史表
    db-history-used: true #为true表示使用历史表，如果不配置，则工程启动后可以检查数据库
    check-process-definitions: false #自动部署
#logging:
#  level:
#    org:
#      activiti:
#        engine:
#          impl:
#            persistence:
#              entity: DEBUG